### PR TITLE
SIMD constructs

### PR DESCRIPTION
**Pull request by patrickf2000**
This adds the OpenMP SIMD construct, and a partial implementation of "omp parallel for simd"; the latter is almost working, it just comes as two separate pragma's so I'll look into that. All tests have been updated.

This should cover issue #54.

### CODE REVIEW

**Comment by ouankou** [comment]
@patrickf2000 Could you please change the base branch to `dev`? We always start the work from the `dev` branch and merge it back to the `dev` branch.

Please fix the CI testing. Otherwise, any further commits from others will fail as well. If the failure is caused by your partial implementation of `parallel for simd`, you may either fix the issue or disable the relevant tests temporarily.

**Comment by patrickf2000** [comment]
@ouankou I changed the base. I didn't realize, but I'll make sure to do that for future pulls.

I'm aware of the failing tests, I'm working on that. The `parallel for simd` doesn't work right now, I thought it was disabled because I made sure to test locally and in an Ubuntu 16 container first I have so I'm not sure why it failed... Anyway, I think I almost have it.

**Comment by yanyh15** [comment]
@patrickf2000 is the `parallel for simd` implemented in the Sage AST?

**Comment by patrickf2000** [comment]
@yanyh15 Yes it is. For some reason, when it is written back out, it is translated like this:
`#pragma omp parallel for simd collapse(2) private(tmp)` becomes:

```
#pragma omp parallel 
#pragma omp for simd  collapse(2) private(tmp)
```

The same thing seems to happen with the regular `omp parallel for`. When you run the tests, it fails because the AST is different. I'm just trying to disable the tests for right now on that.

**Comment by patrickf2000** [comment]
@ouankou Everything's fixed. Sorry that it took all day... Internet went down right before I was going to push earlier

**Comment by ouankou** [comment]
> 
> 
> @ouankou Everything's fixed. Sorry that it took all day... Internet went down right before I was going to push earlier

@patrickf2000 That's great! I'm going to merge the code. If the disabled tests won't be fixed anytime soon, it would be better to open an issue for the record.

**Review by ouankou — APPROVED** [review]

**Pull request merged**
